services:
  - type: web
    name: monitor-electoral-peru
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: CHROME_BIN
        value: /opt/render/project/.render/chrome/opt/google/chrome/chrome
    buildpacks:
      - key: https://github.com/render-oss/render-chrome
      - key: python